---
- name: My playbook for task
  hosts: nodes
  vars_files:
    - vars/users
  tasks:
  - name: Create user
    no_log: True
    user:
      name: "{{ item.key }}"
      password: "{{ item.value.userpass | password_hash('sha512') }}"
      home: "{{ item.value.homedir }}"
      shell: "{{ item.value.shell }}"
      comment: "{{ item.value.comment }}"
      state: present
      update_password: on_create
    with_dict: "{{ users }}"
...