---
- name: My playbook for task
  hosts: nodes
  vars_files:
    - vars/users
  tasks:
  - name: Create user
    user:
      name: "{{ item.key }}"
      password: "{{ item.value.userpass }}"
      home: "{{ item.value.homedir }}"
      shell: "{{ item.value.shell }}"
      comment: "{{ item.value.comment }}"
      state: present
      update_password: on_create
    loop: "{{ users }}"
...